// w10-vue/billboard/src/App.vue
<!-- ============================================
     COMPONENTE PRINCIPAL - APP (VUE)
     ============================================
     Este es el componente raíz que orquesta toda la aplicación.
     
     DIFERENCIAS CON REACT:
     - Usa Composition API (ref, onMounted) en lugar de hooks
     - Template HTML puro en lugar de JSX
     - Directivas (v-if, v-for) en lugar de JavaScript
     - class en lugar de className
-->

<script setup lang="ts">
// ============================================
// IMPORTS
// ============================================
import { ref, onMounted } from 'vue'
import { getMovies } from './api/movies'
import MovieCard from './components/MovieCard.vue'
import type { Movie } from './types/movie'
import './App.css'

// ============================================
// ESTADO DEL COMPONENTE
// ============================================
// ref: Crea una referencia reactiva (similar a useState de React)
// En JavaScript usamos .value, en el template Vue lo hace automático

// Estado para guardar las películas
const movies = ref<Movie[]>([])

// Estado para saber si está cargando
const loading = ref(true)

// ============================================
// FUNCIONES
// ============================================

// Función para cargar las películas desde Supabase
async function loadMovies() {
  loading.value = true
  const data = await getMovies()
  movies.value = data
  loading.value = false
}

// ============================================
// LIFECYCLE HOOKS
// ============================================
// onMounted: Se ejecuta cuando el componente se monta en el DOM
// Similar a useEffect(() => {}, []) en React

onMounted(() => {
  loadMovies()
})
</script>

<template>
  <!-- ============================================
       RENDERIZADO CONDICIONAL
       ============================================
       Vue usa directivas (v-if, v-else-if, v-else)
       en lugar de operadores ternarios o if + return
  -->
  
  <div id="app">
    <!-- Mientras carga, mostramos mensaje -->
    <p v-if="loading" class="loading">Cargando cartelera...</p>

    <!-- Si no hay películas, mostramos mensaje -->
    <p v-else-if="movies.length === 0" class="empty">
      No hay películas en cartelera
    </p>

    <!-- Contenido principal -->
    <template v-else>
      <header class="header">
        <h1>Cartelera de Cine</h1>
      </header>
      <main class="billboard">
        <!-- 
          v-for: Directiva para iterar sobre arrays (similar a .map() en React)
          :key: Vue necesita una key única para optimizar el renderizado
          :movie: Pasamos la prop movie al componente (equivalente a movie={movie})
          
          Nota: En el template no necesitamos movies.value, Vue lo hace automático
        -->
        <MovieCard 
          v-for="movie in movies" 
          :key="movie.id" 
          :movie="movie" 
        />
      </main>
    </template>
  </div>
</template>

// w11-angular/movies/src/app/app.component.ts
// ============================================
// COMPONENTE PRINCIPAL - APP (ANGULAR)
// ============================================
// Este es el componente raíz que orquesta toda la aplicación.
//
// DIFERENCIAS CON REACT/VUE:
// - Angular usa decoradores (@Component)
// - Inyección de dependencias para servicios
// - Lifecycle hooks como métodos de clase (ngOnInit)
// - Template separado del código TypeScript

import { Component, OnInit, inject } from '@angular/core';
import { MovieService } from './services/movie.service';
import { MovieCardComponent } from './components/movie-card/movie-card.component';
import { Movie } from './models/movie';

@Component({
  // ============================================
  // METADATOS DEL COMPONENTE
  // ============================================
  selector: 'app-root',
  standalone: true,
  
  // imports: Componentes y módulos que usa este componente
  // Aquí importamos MovieCardComponent para usarlo en el template
  imports: [MovieCardComponent],
  
  // templateUrl: Archivo HTML separado
  templateUrl: './app.component.html',
  
  // styleUrl: Archivo CSS separado
  styleUrl: './app.component.css'
})
export class AppComponent implements OnInit {
  // ============================================
  // INYECCIÓN DE DEPENDENCIAS
  // ============================================
  // inject() es la forma moderna de inyectar servicios en Angular 14+
  // También se puede usar el constructor tradicional:
  // constructor(private movieService: MovieService) {}
  
  private movieService = inject(MovieService);

  // ============================================
  // ESTADO DEL COMPONENTE
  // ============================================
  // En Angular, el estado son propiedades de la clase.
  //
  // Comparación:
  // React:   const [movies, setMovies] = useState<Movie[]>([])
  // Vue:     const movies = ref<Movie[]>([])
  // Angular: movies: Movie[] = []
  
  movies: Movie[] = [];
  loading = true;

  // ============================================
  // LIFECYCLE HOOK: ngOnInit
  // ============================================
  // Se ejecuta cuando el componente se inicializa.
  //
  // Comparación:
  // React:   useEffect(() => { loadMovies() }, [])
  // Vue:     onMounted(() => { loadMovies() })
  // Angular: ngOnInit() { this.loadMovies() }

  ngOnInit(): void {
    this.loadMovies();
  }

  // ============================================
  // MÉTODO PARA CARGAR PELÍCULAS
  // ============================================
  // La lógica es la misma que en React/Vue,
  // solo cambia la sintaxis para actualizar el estado.

  async loadMovies(): Promise<void> {
    this.loading = true;
    this.movies = await this.movieService.getMovies();
    this.loading = false;
  }
}

<!-- ============================================
     TEMPLATE DEL COMPONENTE PRINCIPAL (ANGULAR)
     ============================================
     Este es el HTML del componente App.
     
     DIFERENCIAS CON REACT/VUE:
     - Condicionales: @if/@else (Angular 17+) o *ngIf
     - Loops: @for (Angular 17+) o *ngFor
     - Binding: [property]="value"
     - Interpolación: {{ variable }}
-->

<div id="app">
  <!-- ============================================
       RENDERIZADO CONDICIONAL
       ============================================
       Angular 17+ usa la nueva sintaxis @if/@else
       Equivalente a:
       - React: {loading && <p>...</p>}
       - Vue:   <p v-if="loading">...</p>
  -->
  
  @if (loading) {
    <!-- Mientras carga, mostramos mensaje -->
    <p class="loading">Cargando cartelera...</p>
  } @else if (movies.length === 0) {
    <!-- Si no hay películas -->
    <p class="empty">No hay películas en cartelera</p>
  } @else {
    <!-- Contenido principal -->
    <header class="header">
      <h1>Cartelera de Cine</h1>
    </header>
    
    <main class="billboard">
      <!-- ============================================
           ITERACIÓN CON @for
           ============================================
           Angular 17+ usa @for en lugar de *ngFor.
           
           Comparación:
           - React: {movies.map(movie => <MovieCard key={movie.id} movie={movie} />)}
           - Vue:   <MovieCard v-for="movie in movies" :key="movie.id" :movie="movie" />
           - Angular: @for (movie of movies; track movie.id) {
                        <app-movie-card [movie]="movie" />
                      }
           
           track: Similar a key en React/Vue, ayuda a Angular
           a identificar elementos y optimizar el renderizado.
      -->
      @for (movie of movies; track movie.id) {
        <app-movie-card [movie]="movie" />
      }
    </main>
  }
</div>
