// w9-react/billboard/src/components/MovieCard.tsx
// ============================================
// COMPONENTE MOVIE CARD (REACT)
// ============================================
// Este componente recibe los datos de una película
// y retorna JSX (similar a HTML pero en React).
// 
// DIFERENCIA CON VANILLA TS:
// - En lugar de retornar un string de HTML,
//   retorna elementos JSX
// - React re-renderiza automáticamente cuando cambian los datos

import type { Movie } from '../types/movie'

// Props: parámetros que recibe el componente
interface MovieCardProps {
  movie: Movie
}

// Componente funcional de React
export function MovieCard({ movie }: MovieCardProps) {
  return (
    <div className="movie-card">
      <img 
        src={movie.image} 
        alt={movie.title} 
        className="movie-poster"
      />
      <div className="movie-info">
        <h3 className="movie-title">{movie.title}</h3>
        <span className="movie-genre">{movie.genre}</span>
        <p className="movie-description">{movie.description}</p>
      </div>
    </div>
  )
}

// w10-vue/billboard/src/components/MovieCard.vue
<!-- ============================================
     COMPONENTE MOVIE CARD (VUE)
     ============================================
     Este componente recibe los datos de una película
     y los muestra en una tarjeta visual.
     
     DIFERENCIA CON REACT:
     - En lugar de una función que retorna JSX,
       Vue usa Single File Components (.vue)
     - Template HTML puro en lugar de JSX
     - defineProps en lugar de interface + desestructuración
     - {{ }} para interpolación en lugar de { }
     - class en lugar de className
     - :src en lugar de src={}
-->

<script setup lang="ts">
// ============================================
// IMPORTS
// ============================================
import type { Movie } from '../types/movie'

// ============================================
// PROPS
// ============================================
// defineProps: Macro de Vue para definir las props
// Es equivalente a:
// interface MovieCardProps { movie: Movie }
// function MovieCard({ movie }: MovieCardProps)

defineProps<{
  movie: Movie
}>()
</script>

<template>
  <!-- ============================================
       TEMPLATE
       ============================================
       HTML puro con directivas de Vue
       
       Diferencias con React JSX:
       - class en lugar de className
       - :src="movie.image" en lugar de src={movie.image}
       - {{ movie.title }} en lugar de {movie.title}
  -->
  
  <div class="movie-card">
    <!-- 
      :src es atajo de v-bind:src
      Enlaza dinámicamente el atributo src con el valor de movie.image
    -->
    <img 
      :src="movie.image" 
      :alt="movie.title" 
      class="movie-poster"
    />
    <div class="movie-info">
      <!-- 
        {{ }} es la sintaxis de interpolación de Vue (mustache syntax)
        Equivalente a {movie.title} en React
      -->
      <h3 class="movie-title">{{ movie.title }}</h3>
      <span class="movie-genre">{{ movie.genre }}</span>
      <p class="movie-description">{{ movie.description }}</p>
    </div>
  </div>
</template>
