// w10-vue/billboard/src/App.vue
<!-- ============================================
     COMPONENTE PRINCIPAL - APP (VUE)
     ============================================
     Este es el componente raíz que orquesta toda la aplicación.
     
     DIFERENCIAS CON REACT:
     - Usa Composition API (ref, onMounted) en lugar de hooks
     - Template HTML puro en lugar de JSX
     - Directivas (v-if, v-for) en lugar de JavaScript
     - class en lugar de className
-->

<script setup lang="ts">
// ============================================
// IMPORTS
// ============================================
import { ref, onMounted } from 'vue'
import { getMovies } from './api/movies'
import MovieCard from './components/MovieCard.vue'
import type { Movie } from './types/movie'
import './App.css'

// ============================================
// ESTADO DEL COMPONENTE
// ============================================
// ref: Crea una referencia reactiva (similar a useState de React)
// En JavaScript usamos .value, en el template Vue lo hace automático

// Estado para guardar las películas
const movies = ref<Movie[]>([])

// Estado para saber si está cargando
const loading = ref(true)

// ============================================
// FUNCIONES
// ============================================

// Función para cargar las películas desde Supabase
async function loadMovies() {
  loading.value = true
  const data = await getMovies()
  movies.value = data
  loading.value = false
}

// ============================================
// LIFECYCLE HOOKS
// ============================================
// onMounted: Se ejecuta cuando el componente se monta en el DOM
// Similar a useEffect(() => {}, []) en React

onMounted(() => {
  loadMovies()
})
</script>

<template>
  <!-- ============================================
       RENDERIZADO CONDICIONAL
       ============================================
       Vue usa directivas (v-if, v-else-if, v-else)
       en lugar de operadores ternarios o if + return
  -->
  
  <div id="app">
    <!-- Mientras carga, mostramos mensaje -->
    <p v-if="loading" class="loading">Cargando cartelera...</p>

    <!-- Si no hay películas, mostramos mensaje -->
    <p v-else-if="movies.length === 0" class="empty">
      No hay películas en cartelera
    </p>

    <!-- Contenido principal -->
    <template v-else>
      <header class="header">
        <h1>Cartelera de Cine</h1>
      </header>
      <main class="billboard">
        <!-- 
          v-for: Directiva para iterar sobre arrays (similar a .map() en React)
          :key: Vue necesita una key única para optimizar el renderizado
          :movie: Pasamos la prop movie al componente (equivalente a movie={movie})
          
          Nota: En el template no necesitamos movies.value, Vue lo hace automático
        -->
        <MovieCard 
          v-for="movie in movies" 
          :key="movie.id" 
          :movie="movie" 
        />
      </main>
    </template>
  </div>
</template>

// w9-react/billboard/src/App.tsx
// ============================================
// COMPONENTE PRINCIPAL - APP (REACT)
// ============================================
// Este es el componente raíz que orquesta toda la aplicación.
//
// DIFERENCIAS CON VANILLA TS:
// - Usa hooks (useState, useEffect) para manejar estado y efectos
// - React maneja el DOM automáticamente
// - No necesitamos innerHTML ni manipulación directa del DOM

import { useState, useEffect } from 'react'
import { getMovies } from './api/movies'
import { MovieCard } from './components/MovieCard'
import type { Movie } from './types/movie'
import './App.css'

function App() {
  // ============================================
  // ESTADO DEL COMPONENTE
  // ============================================
  // useState: Hook que guarda datos que pueden cambiar
  
  // Estado para guardar las películas
  const [movies, setMovies] = useState<Movie[]>([])
  
  // Estado para saber si está cargando
  const [loading, setLoading] = useState(true)

  // ============================================
  // EFECTOS (Side Effects)
  // ============================================
  // useEffect: Hook que ejecuta código cuando el componente se monta
  // Similar a hacer la petición al cargar la página en Vanilla
  
  useEffect(() => {
    // Función asíncrona para cargar las películas
    async function loadMovies() {
      setLoading(true)
      const data = await getMovies()
      setMovies(data)
      setLoading(false)
    }

    // Ejecutamos la función
    loadMovies()
  }, []) // [] significa: ejecutar solo una vez al montar el componente

  // ============================================
  // RENDERIZADO CONDICIONAL
  // ============================================
  
  // Mientras carga, mostramos mensaje
  if (loading) {
    return (
      <div id="app">
        <p className="loading">Cargando cartelera...</p>
      </div>
    )
  }

  // Si no hay películas, mostramos mensaje
  if (movies.length === 0) {
    return (
      <div id="app">
        <p className="empty">No hay películas en cartelera</p>
      </div>
    )
  }

  // ============================================
  // RENDERIZADO PRINCIPAL
  // ============================================
  // JSX: sintaxis similar a HTML pero con superpoderes
  // - Podemos usar {} para insertar código JavaScript
  // - .map() para iterar y crear componentes
  // - className en lugar de class (porque class es palabra reservada en JS)
  
  return (
    <div id="app">
      <header className="header">
        <h1>Cartelera de Cine</h1>
      </header>
      <main className="billboard">
        {/* 
          .map(): Por cada película, creamos un componente MovieCard
          key: React necesita una key única para optimizar el renderizado
        */}
        {movies.map(movie => (
          <MovieCard key={movie.id} movie={movie} />
        ))}
      </main>
    </div>
  )
}

export default App
